export function env(name){return process.env[name]?.trim()||'';}
async function getJson(url,options={}){const r=await fetch(url,{...options,headers:{accept:'application/json',...(options.headers||{})},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('HTTP '+r.status+' from '+new URL(url).hostname);return r.json();}
export function createProviders(){
 const out=[],coin=env('BRAIINS_COIN')||'btc';
 if(env('BRAIINS_POOL_TOKEN'))out.push({name:'braiins',async overview(){const h={'Pool-Auth-Token':env('BRAIINS_POOL_TOKEN')},from=new Date(Date.now()-30*864e5).toISOString().slice(0,10),to=new Date().toISOString().slice(0,10);const [profile,workers,payouts]=await Promise.all([getJson('https://pool.braiins.com/accounts/profile/json/'+coin+'/',{headers:h}),getJson('https://pool.braiins.com/accounts/workers/json/'+coin,{headers:h}),getJson('https://pool.braiins.com/accounts/payouts/json/'+coin+'?from='+from+'&to='+to,{headers:h})]);return{provider:'braiins',coin,source:'Braiins Pool',pool:profile?.[coin]||{},workers:workers?.[coin]?.workers||{},payouts:payouts?.onchain||[]};}});
 if(env('LUXOR_API_KEY'))out.push({name:'luxor',async overview(){const c=(env('LUXOR_CURRENCY')||'BTC').toUpperCase(),base=env('LUXOR_BASE_URL')||'https://app.luxor.tech/api',h={authorization:env('LUXOR_API_KEY')};const [stats,workers]=await Promise.all([getJson(base+'/v2/pool/pool-stats/'+c,{headers:h}),getJson(base+'/v2/pool/workers/'+c+'?page_number=1&page_size=1000',{headers:h})]);return{provider:'luxor',coin:c,source:'Luxor',pool:stats||{},workers:workers?.workers||[],payouts:[]};}});
 if(env('FOUNDRY_API_URL')&&env('FOUNDRY_API_TOKEN'))out.push({name:'foundry',async overview(){const d=await getJson(env('FOUNDRY_API_URL'),{headers:{authorization:'Bearer '+env('FOUNDRY_API_TOKEN')}});return{provider:'foundry',coin:'BTC',source:'Foundry USA',pool:d,workers:d?.workers||[],payouts:d?.payouts||[]};}});
 return out;
}
